service: whitebard-api-mm-billing

# Use the serverless-webpack plugin to transpile ES6
plugins:
- serverless-webpack
- serverless-offline

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ../webpack.config.js
    includeModules: true
  # Load our secret environment variables based on the current stage.
  # Fallback to default if it is not in prod.
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}


provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2

  environment:
    stripeSecretKey: ${self:custom.environment.stripeSecretKey}

functions:
  billing:
    handler: billing.main
    events:
    - http:
        path: billing
        method: post
        cors: true
        authorizer: aws_iam
